name: CI

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    lint-and-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.9, 3.10, 3.11]

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Cache pip dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8 black isort pytest pytest-cov
                  pip install langchain langsmith langchain-community langchain-openai langchain-anthropic
                  pip install langraph streamlit gradio fastapi uvicorn requests pandas numpy matplotlib seaborn
                  pip install jupyter notebook jupyterlab python-dotenv

            - name: Lint with flake8
              run: |
                  flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
                  flake8 src/ --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

            - name: Check formatting with black
              run: black --check src/

            - name: Check import sorting with isort
              run: isort --check-only src/

            - name: Run tests with pytest
              run: |
                  pytest src/ --cov=src --cov-report=xml --cov-report=term-missing

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              with:
                  file: ./coverage.xml
                  flags: unittests