name: Security

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    schedule:
        # Run weekly on Sundays
        - cron: '0 2 * * 0'

jobs:
    security-scan:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.11'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install safety bandit semgrep

            - name: Check for security vulnerabilities in dependencies
              run: |
                  # Create requirements file from postCreateCommand
                  echo "langchain" > requirements.txt
                  echo "langsmith" >> requirements.txt
                  echo "langchain-community" >> requirements.txt
                  echo "langchain-openai" >> requirements.txt
                  echo "langchain-anthropic" >> requirements.txt
                  echo "langraph" >> requirements.txt
                  echo "streamlit" >> requirements.txt
                  echo "gradio" >> requirements.txt
                  echo "fastapi" >> requirements.txt
                  echo "uvicorn" >> requirements.txt
                  echo "requests" >> requirements.txt
                  echo "pandas" >> requirements.txt
                  echo "numpy" >> requirements.txt
                  echo "matplotlib" >> requirements.txt
                  echo "seaborn" >> requirements.txt
                  echo "jupyter" >> requirements.txt
                  echo "notebook" >> requirements.txt
                  echo "jupyterlab" >> requirements.txt
                  echo "python-dotenv" >> requirements.txt
                  
                  safety check --file requirements.txt

            - name: Run Bandit security scan
              run: |
                  bandit -r src/ -f json -o bandit-report.json || true
                  bandit -r src/

            - name: Run Semgrep security scan
              run: |
                  semgrep --config=auto src/ --json --output=semgrep-report.json || true
                  semgrep --config=auto src/

            - name: Upload security scan results
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: security-reports
                  path: |
                      bandit-report.json
                      semgrep-report.json

    dependency-review:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - name: Dependency Review
              uses: actions/dependency-review-action@v4
              with:
                  fail-on-severity: moderate